name: Publish

on:
  push:
    branches: [main, iota]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn

      - name: Test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn test

      - name: Build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          GIT_TOKEN: ${{ secrets.AUTOMATION_PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          git config --global user.name "MSafeAdmin"
          git config --global user.email "admin@m-safe.io"
          git fetch
          git checkout iota
          git clean -df
          git checkout .
          git pull
          npm version patch
          git push --follow-tags --force
          yarn publish --non-interactive --access public
